[snowflake]
account = "ODEUAMO-YKB64805"
user = "sgnillumg"
password = "SnowSwagg42!!!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
